# Generated by Django 2.2 on 2019-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
    ]
