# Generated by Django 2.2 on 2019-04-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_animal_adotado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'verbose_name_plural': 'adoções'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'animais'},
        ),
    ]
