# Generated by Django 2.2 on 2019-11-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_auto_20191102_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='imagens',
            options={'verbose_name_plural': 'Imagens'},
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='nome_animal',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='imagens',
            old_name='imagem_animal',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='cpf_pessoa',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='endereco_pessoa',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome_pessoa',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefone_pessoa',
            new_name='telefone',
        ),
    ]
