# Generated by Django 2.2 on 2019-04-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_auto_20190430_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='raca',
            new_name='especie',
        ),
    ]
