# Generated by Django 2.2 on 2019-10-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0004_auto_20190430_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='imagemAnimal',
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_animal', models.ImageField(upload_to='images/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.Animal')),
            ],
        ),
    ]
