# Generated by Django 2.2 on 2019-12-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0004_auto_20191206_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='castrado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='vacinado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='vermifugado',
        ),
    ]
