# Generated by Django 2.2 on 2019-10-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0005_auto_20191021_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[(3, 'Gato'), (4, 'Cachorro'), (8, 'Nao informado')], default=8, max_length=9),
        ),
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[(5, 'Pequeno'), (6, 'Medio'), (7, 'Grande'), (8, 'Nao informado')], default=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[(1, 'Macho'), (2, 'Femea'), (8, 'Nao informado')], default=8, max_length=6),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='adocao.Animal'),
        ),
    ]
