# Generated by Django 2.2 on 2019-12-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0005_auto_20191211_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
    ]
