# Generated by Django 2.2 on 2019-12-11 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0006_auto_20191211_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['data']},
        ),
        migrations.AddField(
            model_name='animal',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
