# Generated by Django 2.2 on 2019-12-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0007_auto_20191211_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-data']},
        ),
    ]
