# Generated by Django 2.2 on 2019-10-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0007_auto_20191022_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Macho'), (2, 'Femea'), (8, 'Nao informado')], default=8),
        ),
    ]
