# Generated by Django 2.2 on 2019-10-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0008_auto_20191023_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.IntegerField(choices=[(3, 'Gato'), (4, 'Cachorro'), (8, 'Nao informado')], default=8),
        ),
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.IntegerField(choices=[(5, 'Pequeno'), (6, 'Médio'), (7, 'Grande'), (8, 'Nao informado')], default=8),
        ),
    ]
