# Generated by Django 2.2 on 2019-10-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0009_auto_20191023_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Macho'), (2, 'Femea'), (8, 'Nao informado')], default=8, verbose_name='Sexo'),
        ),
    ]
